name: py3-11-13
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13  # Versão especificada
  - pip
  - mlflow=2.13.0   # Versão recente para funcionalidades completas
  - scikit-learn=1.5.0 # Versão recente
  - pandas=2.2.2
  - numpy=1.26.4
  - ipykernel       # Útil se for usar notebooks
  - pip:
    - joblib==1.4.2 # Necessário para persistência de modelos, se não usar o MLflow
    - dotenv
    - loguru
    - typer
    - tqdm
    - -e .
